"""Constantes de opcodes Qix (com.qix.library.command.CommandCode).

Auto-generado por scripts/extract_opcodes.py desde
decompiled/zrun/sources/com/qix/library/command/CommandCode.java
Total: 136 opcodes.
"""

CMD_SET_USER = 0x00
CMD_SET_GOAL = 0x01
CMD_SET_TIME = 0x02
CMD_SET_ALARM_CLOCK = 0x03
CMD_SET_SEDENTARY = 0x04
CMD_SET_DISTURB = 0x05
CMD_SET_BO_DETECT = 0x07
CMD_SET_RAISE_HAND = 0x08
CMD_SET_SYSTEM = 0x09
CMD_SET_HR_ALERT = 0x0A
CMD_SET_HR_DETECT = 0x0B
CMD_SET_DEVICE_FUNCTION = 0x0C
CMD_SET_SPORT_SUPPORT_STEPS = 0x10
CMD_GET_QR_CODE = 0x11
CMD_SET_BP_DETECT = 0x12
CMD_SET_METRIC = 0x13
CMD_SET_DRINK = 0x14
CMD_SET_HOURSYSTEM = 0x15
CMD_SET_LANGUAGE = 0x16
CMD_SET_THEME = 0x19
CMD_SET_CUSTOM_THEME = 0x1A
CMD_SET_BRIGHT_SCREEN = 0x1B
CMD_SET_PUSH_DIAL = 0x1C
CMD_SET_TEMP_DETECT = 0x1D
CMD_SET_SPORT_MODE = 0x1E
CMD_SET_REAL_SYNCH = 0x20
CMD_RET_SYNCH_STATE = 0x21
CMD_RET_STEP_DATA = 0x22
CMD_RET_SLEEP_DATA = 0x23
CMD_RET_HR_DATA = 0x24
CMD_RET_PRESSURE_DATA = 0x25
CMD_RET_OXYGEN_DATA = 0x26
CMD_RET_BATTERY_DATA = 0x27
CMD_RET_FIRMWA_DATA = 0x28
CMD_REQ_DATA = 0x29
CMD_SEND_HEALTH_DETECT = 0x2A
CMD_SEND_WEATHER = 0x2B
CMD_REQ_SPORT_DATA = 0x2D
CMD_REQ_TEMP_TEST = 0x33
CMD_SET_ALIPAY_INFO = 0x34
CMD_SET_PAYMENT_INFO = 0x35
CMD_RET_BS_DATA = 0x36
CMD_RET_UA_DATA = 0x37
CMD_RET_BF_DATA = 0x38
CMD_SET_NOTIFY = 0x40
CMD_SEND_NOTIFY = 0x41
CMD_GET_NOTIFY_TYPE = 0x42
CMD_GET_NOTIFY_STATE = 0x43
CMD_SEND_STOCK_CONTENT = 0x45
CMD_SEND_NEWS_CONTENT = 0x46
CMD_QUERY_QR_CODE = 0x47
CMD_BIND_QR_CODE = 0x48
CMD_GET_VIDEO_DIAL_INFO = 0x49
CMD_GET_VIDEO_ALTITUDE = 0x4A
CMD_SEND_CONTACTS = 0x50
CMD_GET_CONTACTS = 0x52
CMD_REQ_BIND = 0x60
CMD_RET_BIND = 0x61
CMD_REQ_UNBIND = 0x62
CMD_WECHAT_MSG_DEVICE_REQ_INFO = 0x70
CMD_WECHAT_MSG_APP_RSP_INFO = 0x71
CMD_WECHAT_MSG_APP_SEND_INFO = 0x72
CMD_WECHAT_MSG_DEVICE_SEND_INFO = 0x73
CMD_WECHAT_MSG_DEVICE_SEND_INFO_STATE = 0x74
CMD_CON_FIND = 0x80
CMD_CON_CAMERA = 0x81
CMD_CON_MUSIC = 0x82
CMD_CON_CALL = 0x83
CMD_CON_UPGRADE = 0x84
CMD_CON_MAPS = 0x85
CMD_CONRQ_GeoInfo = 0x86
CMD_CON_SendFileSt = 0x87
CMD_CON_TRANSLATOR = 0x88
CMD_SET_BOOT_ANI = 0x8A
CMD_RET_PAY_AUTH_STATUS = 0x8B
CMD_CON_AI_RECORD = 0x8C
CMD_CON_INTERPRETATION = 0x8D
CMD_CON_AI_CONFIG = 0x8E
CMD_MARK = 0x9E
CMD_SET_TEST_MODE = 0xA0
CMD_TEST_MOTOR = 0xA1
CMD_TEST_LOED = 0xA2
CMD_TEST_GSENSOR = 0xA3
CMD_NOTIFICATION_SEND = 0xA4
CMD_TEST_HR = 0xA4
CMD_TEST_RESTORE = 0xA5
CMD_TEST_CLOSE = 0xA6
CMD_TEST_UNTIED = 0xA7
CMD_TEST_RESTART = 0xA8
CMD_TEST_GET_MEMORY = 0xA9
CMD_TEST_GET_FLASH = 0xAA
CMD_TEST_GET_FLASH_RECORD1 = 0xAB
CMD_TEST_GET_FLASH_RECORD2 = 0xAC
CMD_TEST_GET_FLASH_RECORD3 = 0xAD
CMD_TEST_GET_RAM = 0xAE
CMD_TEST_GET_USER_CONFIG = 0xAF
CMD_TEST_SET_MOTION_STATE = 0xB0
CMD_SYNCHRO_SENSOR_DATA = 0xB1
CMD_TEST_SET_SLEEP_STATE = 0xB1
CMD_TEST_SYNCH_MOTION_DATA = 0xB2
CMD_TEST_SYNCH_SLEEP_DATA = 0xB3
CMD_TEST_SYNCH_GSENSOR_STATE = 0xB4
CMD_TEST_RESPONSE_GSENSOR = 0xB5
CMD_TEST_SET_BROADCAST_DATA = 0xB6
CMD_TEST_SET_ADDRESS = 0xB7
CMD_TEST_REQUEST = 0xB8
CMD_TEST_RESPONSE = 0xB9
CMD_TEST_TEMP_CALIBRATE = 0xBA
CMD_REQ_UPDATE = 0xC0
CMD_RET_UPDATE = 0xC1
CMD_SEND_UPDATE_DATA = 0xC2
CMD_TIME_SET = 0xC2
CMD_RET_UPDATE_DATA = 0xC3
CMD_REQ_UPDATE_CON = 0xC4
CMD_RET_UPDATE_RESULT = 0xC5
CMD_REQ_BADGE_INFO = 0xC6
CMD_REP_BADGE_INFO = 0xC7
CMD_REQ_ALARM_RING = 0xD6
CMD_SET_MENS_CYCLE = 0xD7
CMD_SET_GeoInfo = 0xD8
CMD_REQ_PICTURE_SIZE = 0xDA
CMD_SET_SEND_FILE_TYPE = 0xDC
CMD_SEND_NAVIGATION = 0xDF
CMD_RET_CHATAI = 0xE0
CMD_RET_CHATAI_VSTREAM = 0xE1
CMD_SEND_CHATAI_OPST = 0xE3
CMD_SEND_CHATAI_REQTXT = 0xE4
CMD_SEND_CHATAI_RESTXT = 0xE5
CMD_RET_AI_DIAL_CMD = 0xE8
CMD_RET_AI_DIAL_STYLE = 0xE9
CMD_RET_AI_DIAL_INFO = 0xEA
CMD_RET_AI_DIAL_VTXT = 0xEB
CMD_RET_AI_DIAL_MAKE = 0xEC
CMD_RET_AI_DIAL_MAKEST = 0xED
CMD_OPEN_SENSOR = 0xFF
CMD_SEND_RESPONSE = 0xFF

CMD_NAMES: dict[int, str] = {
    0x00: 'CMD_SET_USER',
    0x01: 'CMD_SET_GOAL',
    0x02: 'CMD_SET_TIME',
    0x03: 'CMD_SET_ALARM_CLOCK',
    0x04: 'CMD_SET_SEDENTARY',
    0x05: 'CMD_SET_DISTURB',
    0x07: 'CMD_SET_BO_DETECT',
    0x08: 'CMD_SET_RAISE_HAND',
    0x09: 'CMD_SET_SYSTEM',
    0x0A: 'CMD_SET_HR_ALERT',
    0x0B: 'CMD_SET_HR_DETECT',
    0x0C: 'CMD_SET_DEVICE_FUNCTION',
    0x10: 'CMD_SET_SPORT_SUPPORT_STEPS',
    0x11: 'CMD_GET_QR_CODE',
    0x12: 'CMD_SET_BP_DETECT',
    0x13: 'CMD_SET_METRIC',
    0x14: 'CMD_SET_DRINK',
    0x15: 'CMD_SET_HOURSYSTEM',
    0x16: 'CMD_SET_LANGUAGE',
    0x19: 'CMD_SET_THEME',
    0x1A: 'CMD_SET_CUSTOM_THEME',
    0x1B: 'CMD_SET_BRIGHT_SCREEN',
    0x1C: 'CMD_SET_PUSH_DIAL',
    0x1D: 'CMD_SET_TEMP_DETECT',
    0x1E: 'CMD_SET_SPORT_MODE',
    0x20: 'CMD_SET_REAL_SYNCH',
    0x21: 'CMD_RET_SYNCH_STATE',
    0x22: 'CMD_RET_STEP_DATA',
    0x23: 'CMD_RET_SLEEP_DATA',
    0x24: 'CMD_RET_HR_DATA',
    0x25: 'CMD_RET_PRESSURE_DATA',
    0x26: 'CMD_RET_OXYGEN_DATA',
    0x27: 'CMD_RET_BATTERY_DATA',
    0x28: 'CMD_RET_FIRMWA_DATA',
    0x29: 'CMD_REQ_DATA',
    0x2A: 'CMD_SEND_HEALTH_DETECT',
    0x2B: 'CMD_SEND_WEATHER',
    0x2D: 'CMD_REQ_SPORT_DATA',
    0x33: 'CMD_REQ_TEMP_TEST',
    0x34: 'CMD_SET_ALIPAY_INFO',
    0x35: 'CMD_SET_PAYMENT_INFO',
    0x36: 'CMD_RET_BS_DATA',
    0x37: 'CMD_RET_UA_DATA',
    0x38: 'CMD_RET_BF_DATA',
    0x40: 'CMD_SET_NOTIFY',
    0x41: 'CMD_SEND_NOTIFY',
    0x42: 'CMD_GET_NOTIFY_TYPE',
    0x43: 'CMD_GET_NOTIFY_STATE',
    0x45: 'CMD_SEND_STOCK_CONTENT',
    0x46: 'CMD_SEND_NEWS_CONTENT',
    0x47: 'CMD_QUERY_QR_CODE',
    0x48: 'CMD_BIND_QR_CODE',
    0x49: 'CMD_GET_VIDEO_DIAL_INFO',
    0x4A: 'CMD_GET_VIDEO_ALTITUDE',
    0x50: 'CMD_SEND_CONTACTS',
    0x52: 'CMD_GET_CONTACTS',
    0x60: 'CMD_REQ_BIND',
    0x61: 'CMD_RET_BIND',
    0x62: 'CMD_REQ_UNBIND',
    0x70: 'CMD_WECHAT_MSG_DEVICE_REQ_INFO',
    0x71: 'CMD_WECHAT_MSG_APP_RSP_INFO',
    0x72: 'CMD_WECHAT_MSG_APP_SEND_INFO',
    0x73: 'CMD_WECHAT_MSG_DEVICE_SEND_INFO',
    0x74: 'CMD_WECHAT_MSG_DEVICE_SEND_INFO_STATE',
    0x80: 'CMD_CON_FIND',
    0x81: 'CMD_CON_CAMERA',
    0x82: 'CMD_CON_MUSIC',
    0x83: 'CMD_CON_CALL',
    0x84: 'CMD_CON_UPGRADE',
    0x85: 'CMD_CON_MAPS',
    0x86: 'CMD_CONRQ_GeoInfo',
    0x87: 'CMD_CON_SendFileSt',
    0x88: 'CMD_CON_TRANSLATOR',
    0x8A: 'CMD_SET_BOOT_ANI',
    0x8B: 'CMD_RET_PAY_AUTH_STATUS',
    0x8C: 'CMD_CON_AI_RECORD',
    0x8D: 'CMD_CON_INTERPRETATION',
    0x8E: 'CMD_CON_AI_CONFIG',
    0x9E: 'CMD_MARK',
    0xA0: 'CMD_SET_TEST_MODE',
    0xA1: 'CMD_TEST_MOTOR',
    0xA2: 'CMD_TEST_LOED',
    0xA3: 'CMD_TEST_GSENSOR',
    0xA4: 'CMD_NOTIFICATION_SEND',
    0xA4: 'CMD_TEST_HR',
    0xA5: 'CMD_TEST_RESTORE',
    0xA6: 'CMD_TEST_CLOSE',
    0xA7: 'CMD_TEST_UNTIED',
    0xA8: 'CMD_TEST_RESTART',
    0xA9: 'CMD_TEST_GET_MEMORY',
    0xAA: 'CMD_TEST_GET_FLASH',
    0xAB: 'CMD_TEST_GET_FLASH_RECORD1',
    0xAC: 'CMD_TEST_GET_FLASH_RECORD2',
    0xAD: 'CMD_TEST_GET_FLASH_RECORD3',
    0xAE: 'CMD_TEST_GET_RAM',
    0xAF: 'CMD_TEST_GET_USER_CONFIG',
    0xB0: 'CMD_TEST_SET_MOTION_STATE',
    0xB1: 'CMD_SYNCHRO_SENSOR_DATA',
    0xB1: 'CMD_TEST_SET_SLEEP_STATE',
    0xB2: 'CMD_TEST_SYNCH_MOTION_DATA',
    0xB3: 'CMD_TEST_SYNCH_SLEEP_DATA',
    0xB4: 'CMD_TEST_SYNCH_GSENSOR_STATE',
    0xB5: 'CMD_TEST_RESPONSE_GSENSOR',
    0xB6: 'CMD_TEST_SET_BROADCAST_DATA',
    0xB7: 'CMD_TEST_SET_ADDRESS',
    0xB8: 'CMD_TEST_REQUEST',
    0xB9: 'CMD_TEST_RESPONSE',
    0xBA: 'CMD_TEST_TEMP_CALIBRATE',
    0xC0: 'CMD_REQ_UPDATE',
    0xC1: 'CMD_RET_UPDATE',
    0xC2: 'CMD_SEND_UPDATE_DATA',
    0xC2: 'CMD_TIME_SET',
    0xC3: 'CMD_RET_UPDATE_DATA',
    0xC4: 'CMD_REQ_UPDATE_CON',
    0xC5: 'CMD_RET_UPDATE_RESULT',
    0xC6: 'CMD_REQ_BADGE_INFO',
    0xC7: 'CMD_REP_BADGE_INFO',
    0xD6: 'CMD_REQ_ALARM_RING',
    0xD7: 'CMD_SET_MENS_CYCLE',
    0xD8: 'CMD_SET_GeoInfo',
    0xDA: 'CMD_REQ_PICTURE_SIZE',
    0xDC: 'CMD_SET_SEND_FILE_TYPE',
    0xDF: 'CMD_SEND_NAVIGATION',
    0xE0: 'CMD_RET_CHATAI',
    0xE1: 'CMD_RET_CHATAI_VSTREAM',
    0xE3: 'CMD_SEND_CHATAI_OPST',
    0xE4: 'CMD_SEND_CHATAI_REQTXT',
    0xE5: 'CMD_SEND_CHATAI_RESTXT',
    0xE8: 'CMD_RET_AI_DIAL_CMD',
    0xE9: 'CMD_RET_AI_DIAL_STYLE',
    0xEA: 'CMD_RET_AI_DIAL_INFO',
    0xEB: 'CMD_RET_AI_DIAL_VTXT',
    0xEC: 'CMD_RET_AI_DIAL_MAKE',
    0xED: 'CMD_RET_AI_DIAL_MAKEST',
    0xFF: 'CMD_OPEN_SENSOR',
    0xFF: 'CMD_SEND_RESPONSE',
}
